<?php

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'id' => 1,
                'data_type_id' => 1,
                'field' => 'id',
                'type'         => 'number',
                'display_name' => 'ID',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details' => NULL,
                'order'        => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'data_type_id' => 1,
                'field' => 'name',
                'type'         => 'text',
                'display_name' => 'Name',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details' => NULL,
                'order'        => 2,
            ),
            2 => 
            array (
                'id' => 3,
                'data_type_id' => 1,
                'field' => 'email',
                'type'         => 'text',
                'display_name' => 'Email',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details' => NULL,
                'order'        => 3,
            ),
            3 => 
            array (
                'id' => 4,
                'data_type_id' => 1,
                'field' => 'password',
                'type'         => 'password',
                'display_name' => 'Password',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 0,
                'details' => NULL,
                'order'        => 4,
            ),
            4 => 
            array (
                'id' => 5,
                'data_type_id' => 1,
                'field' => 'remember_token',
                'type'         => 'text',
                'display_name' => 'Remember Token',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details' => NULL,
                'order'        => 5,
            ),
            5 => 
            array (
                'id' => 6,
                'data_type_id' => 1,
                'field' => 'created_at',
                'type'         => 'timestamp',
                'display_name' => 'Created At',
                'required'     => 0,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details' => NULL,
                'order'        => 6,
            ),
            6 => 
            array (
                'id' => 7,
                'data_type_id' => 1,
                'field' => 'updated_at',
                'type'         => 'timestamp',
                'display_name' => 'Updated At',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details' => NULL,
                'order'        => 7,
            ),
            7 => 
            array (
                'id' => 8,
                'data_type_id' => 1,
                'field' => 'avatar',
                'type'         => 'image',
                'display_name' => 'Avatar',
                'required'     => 0,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details' => NULL,
                'order'        => 8,
            ),
            8 => 
            array (
                'id' => 9,
                'data_type_id' => 1,
                'field' => 'user_belongsto_role_relationship',
                'type'         => 'relationship',
                'display_name' => 'Role',
                'required'     => 0,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"roles","pivot":0}',
                'order'        => 10,
            ),
            9 => 
            array (
                'id' => 10,
                'data_type_id' => 1,
                'field' => 'user_belongstomany_role_relationship',
                'type'         => 'relationship',
                'display_name' => 'Roles',
                'required'     => 0,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"0"}',
                'order'        => 11,
            ),
            10 => 
            array (
                'id' => 11,
                'data_type_id' => 1,
                'field' => 'settings',
                'type'         => 'hidden',
                'display_name' => 'Settings',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details' => NULL,
                'order'        => 12,
            ),
            11 => 
            array (
                'id' => 12,
                'data_type_id' => 2,
                'field' => 'id',
                'type'         => 'number',
                'display_name' => 'ID',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details' => NULL,
                'order'        => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'data_type_id' => 2,
                'field' => 'name',
                'type'         => 'text',
                'display_name' => 'Name',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details' => NULL,
                'order'        => 2,
            ),
            13 => 
            array (
                'id' => 14,
                'data_type_id' => 2,
                'field' => 'created_at',
                'type'         => 'timestamp',
                'display_name' => 'Created At',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details' => NULL,
                'order'        => 3,
            ),
            14 => 
            array (
                'id' => 15,
                'data_type_id' => 2,
                'field' => 'updated_at',
                'type'         => 'timestamp',
                'display_name' => 'Updated At',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details' => NULL,
                'order'        => 4,
            ),
            15 => 
            array (
                'id' => 16,
                'data_type_id' => 3,
                'field' => 'id',
                'type'         => 'number',
                'display_name' => 'ID',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details' => NULL,
                'order'        => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'data_type_id' => 3,
                'field' => 'name',
                'type'         => 'text',
                'display_name' => 'Name',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details' => NULL,
                'order'        => 2,
            ),
            17 => 
            array (
                'id' => 18,
                'data_type_id' => 3,
                'field' => 'created_at',
                'type'         => 'timestamp',
                'display_name' => 'Created At',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details' => NULL,
                'order'        => 3,
            ),
            18 => 
            array (
                'id' => 19,
                'data_type_id' => 3,
                'field' => 'updated_at',
                'type'         => 'timestamp',
                'display_name' => 'Updated At',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details' => NULL,
                'order'        => 4,
            ),
            19 => 
            array (
                'id' => 20,
                'data_type_id' => 3,
                'field' => 'display_name',
                'type'         => 'text',
                'display_name' => 'Display Name',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details' => NULL,
                'order'        => 5,
            ),
            20 => 
            array (
                'id' => 21,
                'data_type_id' => 1,
                'field' => 'role_id',
                'type'         => 'text',
                'display_name' => 'Role',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details' => NULL,
                'order'        => 9,
            ),
            21 => 
            array (
                'id' => 22,
                'data_type_id' => 4,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            22 => 
            array (
                'id' => 23,
                'data_type_id' => 4,
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Title',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            23 => 
            array (
                'id' => 24,
                'data_type_id' => 4,
                'field' => 'level',
                'type' => 'select_dropdown',
                'display_name' => 'Level',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"options":{"Level 1":"Level 1","Level 2":"Level 2"}}',
                'order' => 3,
            ),
            24 => 
            array (
                'id' => 25,
                'data_type_id' => 4,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            25 => 
            array (
                'id' => 26,
                'data_type_id' => 4,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            26 => 
            array (
                'id' => 27,
                'data_type_id' => 6,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            27 => 
            array (
                'id' => 28,
                'data_type_id' => 6,
                'field' => 'term_id',
                'type' => 'select_dropdown',
                'display_name' => 'Term Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            28 => 
            array (
                'id' => 29,
                'data_type_id' => 6,
                'field' => 'relation_id',
                'type' => 'select_dropdown',
                'display_name' => 'Relation Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            29 => 
            array (
                'id' => 30,
                'data_type_id' => 6,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            30 => 
            array (
                'id' => 31,
                'data_type_id' => 6,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            31 => 
            array (
                'id' => 32,
                'data_type_id' => 6,
                'field' => 'industry_relation_belongsto_industry_relationship',
                'type' => 'relationship',
                'display_name' => 'Industry',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Industry","table":"industries","type":"belongsTo","column":"term_id","key":"id","label":"title","pivot_table":"data_rows","pivot":"0","taggable":"0"}',
                'order' => 6,
            ),
            32 => 
            array (
                'id' => 33,
                'data_type_id' => 6,
                'field' => 'industry_relation_belongsto_industry_relationship_1',
                'type' => 'relationship',
                'display_name' => 'Is Related to Industry',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Industry","table":"industries","type":"belongsTo","column":"relation_id","key":"id","label":"title","pivot_table":"data_rows","pivot":"0","taggable":"0"}',
                'order' => 7,
            ),
            33 => 
            array (
                'id' => 34,
                'data_type_id' => 7,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            34 => 
            array (
                'id' => 35,
                'data_type_id' => 7,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            35 => 
            array (
                'id' => 36,
                'data_type_id' => 7,
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Title',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            36 => 
            array (
                'id' => 37,
                'data_type_id' => 7,
                'field' => 'language',
                'type' => 'text',
                'display_name' => 'Language',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            37 => 
            array (
                'id' => 38,
                'data_type_id' => 7,
                'field' => 'credits',
                'type' => 'number',
                'display_name' => 'Credits',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            38 => 
            array (
                'id' => 39,
                'data_type_id' => 7,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ),
            39 => 
            array (
                'id' => 40,
                'data_type_id' => 7,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            40 => 
            array (
                'id' => 41,
                'data_type_id' => 7,
                'field' => 'color',
                'type' => 'color',
                'display_name' => 'Color',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 8,
            ),
            41 => 
            array (
                'id' => 42,
                'data_type_id' => 7,
                'field' => 'upper_title',
                'type' => 'text',
                'display_name' => 'Upper Title',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 9,
            ),
            42 => 
            array (
                'id' => 43,
                'data_type_id' => 7,
                'field' => 'lower_title',
                'type' => 'text',
                'display_name' => 'Lower Title',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 10,
            ),
            43 => 
            array (
                'id' => 44,
                'data_type_id' => 7,
                'field' => 'price',
                'type' => 'number',
                'display_name' => 'Price',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 11,
            ),
            44 => 
            array (
                'id' => 45,
                'data_type_id' => 7,
                'field' => 'description',
                'type' => 'rich_text_box',
                'display_name' => 'Description',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 12,
            ),
            45 => 
            array (
                'id' => 46,
                'data_type_id' => 7,
                'field' => 'position',
                'type' => 'number',
                'display_name' => 'Position',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 13,
            ),
            46 => 
            array (
                'id' => 47,
                'data_type_id' => 8,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            47 => 
            array (
                'id' => 48,
                'data_type_id' => 8,
                'field' => 'description',
                'type' => 'text',
                'display_name' => 'Description',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            48 => 
            array (
                'id' => 49,
                'data_type_id' => 8,
                'field' => 'user_id',
                'type' => 'text',
                'display_name' => 'User Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            49 => 
            array (
                'id' => 50,
                'data_type_id' => 8,
                'field' => 'package_id',
                'type' => 'text',
                'display_name' => 'Package Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            50 => 
            array (
                'id' => 51,
                'data_type_id' => 8,
                'field' => 'price',
                'type' => 'text',
                'display_name' => 'Price',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            51 => 
            array (
                'id' => 52,
                'data_type_id' => 8,
                'field' => 'credits',
                'type' => 'text',
                'display_name' => 'Credits',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ),
            52 => 
            array (
                'id' => 53,
                'data_type_id' => 8,
                'field' => 'status',
                'type' => 'text',
                'display_name' => 'Status',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
            53 => 
            array (
                'id' => 54,
                'data_type_id' => 8,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 8,
            ),
            54 => 
            array (
                'id' => 55,
                'data_type_id' => 8,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            55 => 
            array (
                'id' => 56,
                'data_type_id' => 8,
                'field' => 'invoice_belongsto_package_relationship',
                'type' => 'relationship',
                'display_name' => 'packages',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Package","table":"packages","type":"belongsTo","column":"package_id","key":"id","label":"name","pivot_table":"brandbooks","pivot":"0","taggable":null}',
                'order' => 10,
            ),
            56 => 
            array (
                'id' => 57,
                'data_type_id' => 8,
                'field' => 'invoice_belongsto_user_relationship',
                'type' => 'relationship',
                'display_name' => 'users',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"user_id","key":"id","label":"name","pivot_table":"brandbooks","pivot":"0","taggable":null}',
                'order' => 11,
            ),
            57 => 
            array (
                'id' => 58,
                'data_type_id' => 4,
                'field' => 'icon',
                'type' => 'select_dropdown',
                'display_name' => 'Icon',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"options":{"ad":"Ad","address-book":"Address Book","address-card":"Address Card","adjust":"Adjust","air-freshener":"Air Freshener","align-center":"Align Center","align-justify":"Align Justify","align-left":"Align Left","align-right":"Align Right","allergies":"Allergies","ambulance":"Ambulance","american-sign-language-interpreting":"American Sign Language Interpreting","anchor":"Anchor","angle-double-down":"Angle Double Down","angle-double-left":"Angle Double Left","angle-double-right":"Angle Double Right","angle-double-up":"Angle Double Up","angle-down":"Angle Down","angle-left":"Angle Left","angle-right":"Angle Right","angle-up":"Angle Up","angry":"Angry","ankh":"Ankh","apple-alt":"Apple Alt","archive":"Archive","archway":"Archway","arrow-alt-circle-down":"Arrow Alt Circle Down","arrow-alt-circle-left":"Arrow Alt Circle Left","arrow-alt-circle-right":"Arrow Alt Circle Right","arrow-alt-circle-up":"Arrow Alt Circle Up","arrow-circle-down":"Arrow Circle Down","arrow-circle-left":"Arrow Circle Left","arrow-circle-right":"Arrow Circle Right","arrow-circle-up":"Arrow Circle Up","arrow-down":"Arrow Down","arrow-left":"Arrow Left","arrow-right":"Arrow Right","arrow-up":"Arrow Up","arrows-alt":"Arrows Alt","arrows-alt-h":"Arrows Alt H","arrows-alt-v":"Arrows Alt V","assistive-listening-systems":"Assistive Listening Systems","asterisk":"Asterisk","at":"At","atlas":"Atlas","atom":"Atom","audio-description":"Audio Description","award":"Award","baby":"Baby","baby-carriage":"Baby Carriage","backspace":"Backspace","backward":"Backward","bacon":"Bacon","bahai":"Bahai","balance-scale":"Balance Scale","balance-scale-left":"Balance Scale Left","balance-scale-right":"Balance Scale Right","ban":"Ban","band-aid":"Band Aid","barcode":"Barcode","bars":"Bars","baseball-ball":"Baseball Ball","basketball-ball":"Basketball Ball","bath":"Bath","battery-empty":"Battery Empty","battery-full":"Battery Full","battery-half":"Battery Half","battery-quarter":"Battery Quarter","battery-three-quarters":"Battery Three Quarters","bed":"Bed","beer":"Beer","bell":"Bell","bell-slash":"Bell Slash","bezier-curve":"Bezier Curve","bible":"Bible","bicycle":"Bicycle","biking":"Biking","binoculars":"Binoculars","biohazard":"Biohazard","birthday-cake":"Birthday Cake","blender":"Blender","blender-phone":"Blender Phone","blind":"Blind","blog":"Blog","bold":"Bold","bolt":"Bolt","bomb":"Bomb","bone":"Bone","bong":"Bong","book":"Book","book-dead":"Book Dead","book-medical":"Book Medical","book-open":"Book Open","book-reader":"Book Reader","bookmark":"Bookmark","border-all":"Border All","\\uf850none":"\\uf850none","border-style":"Border Style","bowling-ball":"Bowling Ball","box":"Box","box-open":"Box Open","boxes":"Boxes","braille":"Braille","brain":"Brain","bread-slice":"Bread Slice","briefcase":"Briefcase","briefcase-medical":"Briefcase Medical","broadcast-tower":"Broadcast Tower","broom":"Broom","brush":"Brush","bug":"Bug","building":"Building","bullhorn":"Bullhorn","bullseye":"Bullseye","burn":"Burn","bus":"Bus","bus-alt":"Bus Alt","business-time":"Business Time","calculator":"Calculator","calendar":"Calendar","calendar-alt":"Calendar Alt","calendar-check":"Calendar Check","calendar-day":"Calendar Day","calendar-minus":"Calendar Minus","calendar-plus":"Calendar Plus","calendar-times":"Calendar Times","calendar-week":"Calendar Week","camera":"Camera","camera-retro":"Camera Retro","campground":"Campground","candy-cane":"Candy Cane","cannabis":"Cannabis","capsules":"Capsules","car":"Car","car-alt":"Car Alt","car-battery":"Car Battery","car-crash":"Car Crash","car-side":"Car Side","caravan":"Caravan","caret-down":"Caret Down","caret-left":"Caret Left","caret-right":"Caret Right","caret-square-down":"Caret Square Down","caret-square-left":"Caret Square Left","caret-square-right":"Caret Square Right","caret-square-up":"Caret Square Up","caret-up":"Caret Up","carrot":"Carrot","cart-arrow-down":"Cart Arrow Down","cart-plus":"Cart Plus","cash-register":"Cash Register","cat":"Cat","certificate":"Certificate","chair":"Chair","chalkboard":"Chalkboard","chalkboard-teacher":"Chalkboard Teacher","charging-station":"Charging Station","chart-area":"Chart Area","chart-bar":"Chart Bar","chart-line":"Chart Line","chart-pie":"Chart Pie","check":"Check","check-circle":"Check Circle","check-double":"Check Double","check-square":"Check Square","cheese":"Cheese","chess":"Chess","chess-bishop":"Chess Bishop","chess-board":"Chess Board","chess-king":"Chess King","chess-knight":"Chess Knight","chess-pawn":"Chess Pawn","chess-queen":"Chess Queen","chess-rook":"Chess Rook","chevron-circle-down":"Chevron Circle Down","chevron-circle-left":"Chevron Circle Left","chevron-circle-right":"Chevron Circle Right","chevron-circle-up":"Chevron Circle Up","chevron-down":"Chevron Down","chevron-left":"Chevron Left","chevron-right":"Chevron Right","chevron-up":"Chevron Up","child":"Child","church":"Church","circle":"Circle","circle-notch":"Circle Notch","city":"City","clinic-medical":"Clinic Medical","clipboard":"Clipboard","clipboard-check":"Clipboard Check","clipboard-list":"Clipboard List","clock":"Clock","clone":"Clone","closed-captioning":"Closed Captioning","cloud":"Cloud","cloud-download-alt":"Cloud Download Alt","cloud-meatball":"Cloud Meatball","cloud-moon":"Cloud Moon","cloud-moon-rain":"Cloud Moon Rain","cloud-rain":"Cloud Rain","cloud-showers-heavy":"Cloud Showers Heavy","cloud-sun":"Cloud Sun","cloud-sun-rain":"Cloud Sun Rain","cloud-upload-alt":"Cloud Upload Alt","cocktail":"Cocktail","code":"Code","code-branch":"Code Branch","coffee":"Coffee","cog":"Cog","cogs":"Cogs","coins":"Coins","columns":"Columns","comment":"Comment","comment-alt":"Comment Alt","comment-dollar":"Comment Dollar","comment-dots":"Comment Dots","comment-medical":"Comment Medical","comment-slash":"Comment Slash","comments":"Comments","comments-dollar":"Comments Dollar","compact-disc":"Compact Disc","compass":"Compass","compress":"Compress","compress-alt":"Compress Alt","compress-arrows-alt":"Compress Arrows Alt","concierge-bell":"Concierge Bell","cookie":"Cookie","cookie-bite":"Cookie Bite","copy":"Copy","copyright":"Copyright","couch":"Couch","credit-card":"Credit Card","crop":"Crop","crop-alt":"Crop Alt","cross":"Cross","crosshairs":"Crosshairs","crow":"Crow","crown":"Crown","crutch":"Crutch","cube":"Cube","cubes":"Cubes","cut":"Cut","database":"Database","deaf":"Deaf","democrat":"Democrat","desktop":"Desktop","dharmachakra":"Dharmachakra","diagnoses":"Diagnoses","dice":"Dice","dice-d20":"Dice D20","dice-d6":"Dice D6","dice-five":"Dice Five","dice-four":"Dice Four","dice-one":"Dice One","dice-six":"Dice Six","dice-three":"Dice Three","dice-two":"Dice Two","digital-tachograph":"Digital Tachograph","directions":"Directions","divide":"Divide","dizzy":"Dizzy","dna":"Dna","dog":"Dog","dollar-sign":"Dollar Sign","dolly":"Dolly","dolly-flatbed":"Dolly Flatbed","donate":"Donate","door-closed":"Door Closed","door-open":"Door Open","dot-circle":"Dot Circle","dove":"Dove","download":"Download","drafting-compass":"Drafting Compass","dragon":"Dragon","draw-polygon":"Draw Polygon","drum":"Drum","drum-steelpan":"Drum Steelpan","drumstick-bite":"Drumstick Bite","dumbbell":"Dumbbell","dumpster":"Dumpster","dumpster-fire":"Dumpster Fire","dungeon":"Dungeon","edit":"Edit","egg":"Egg","eject":"Eject","ellipsis-h":"Ellipsis H","ellipsis-v":"Ellipsis V","envelope":"Envelope","envelope-open":"Envelope Open","envelope-open-text":"Envelope Open Text","envelope-square":"Envelope Square","equals":"Equals","eraser":"Eraser","ethernet":"Ethernet","euro-sign":"Euro Sign","exchange-alt":"Exchange Alt","exclamation":"Exclamation","exclamation-circle":"Exclamation Circle","exclamation-triangle":"Exclamation Triangle","expand":"Expand","expand-alt":"Expand Alt","expand-arrows-alt":"Expand Arrows Alt","external-link-alt":"External Link Alt","external-link-square-alt":"External Link Square Alt","eye":"Eye","eye-dropper":"Eye Dropper","eye-slash":"Eye Slash","fast-backward":"Fast Backward","fast-forward":"Fast Forward","fax":"Fax","feather":"Feather","feather-alt":"Feather Alt","female":"Female","fighter-jet":"Fighter Jet","file":"File","file-alt":"File Alt","file-archive":"File Archive","file-audio":"File Audio","file-code":"File Code","file-contract":"File Contract","file-csv":"File Csv","file-download":"File Download","file-excel":"File Excel","file-export":"File Export","file-image":"File Image","file-import":"File Import","file-invoice":"File Invoice","file-invoice-dollar":"File Invoice Dollar","file-medical":"File Medical","file-medical-alt":"File Medical Alt","file-pdf":"File Pdf","file-powerpoint":"File Powerpoint","file-prescription":"File Prescription","file-signature":"File Signature","file-upload":"File Upload","file-video":"File Video","file-word":"File Word","fill":"Fill","fill-drip":"Fill Drip","film":"Film","filter":"Filter","fingerprint":"Fingerprint","fire":"Fire","fire-alt":"Fire Alt","fire-extinguisher":"Fire Extinguisher","first-aid":"First Aid","fish":"Fish","fist-raised":"Fist Raised","flag":"Flag","flag-checkered":"Flag Checkered","flag-usa":"Flag Usa","flask":"Flask","flushed":"Flushed","folder":"Folder","folder-minus":"Folder Minus","folder-open":"Folder Open","folder-plus":"Folder Plus","font":"Font","football-ball":"Football Ball","forward":"Forward","frog":"Frog","frown":"Frown","frown-open":"Frown Open","funnel-dollar":"Funnel Dollar","futbol":"Futbol","gamepad":"Gamepad","gas-pump":"Gas Pump","gavel":"Gavel","gem":"Gem","genderless":"Genderless","ghost":"Ghost","gift":"Gift","gifts":"Gifts","glass-cheers":"Glass Cheers","glass-martini":"Glass Martini","glass-martini-alt":"Glass Martini Alt","glass-whiskey":"Glass Whiskey","glasses":"Glasses","globe":"Globe","globe-africa":"Globe Africa","globe-americas":"Globe Americas","globe-asia":"Globe Asia","globe-europe":"Globe Europe","golf-ball":"Golf Ball","gopuram":"Gopuram","graduation-cap":"Graduation Cap","greater-than":"Greater Than","greater-than-equal":"Greater Than Equal","grimace":"Grimace","grin":"Grin","grin-alt":"Grin Alt","grin-beam":"Grin Beam","grin-beam-sweat":"Grin Beam Sweat","grin-hearts":"Grin Hearts","grin-squint":"Grin Squint","grin-squint-tears":"Grin Squint Tears","grin-stars":"Grin Stars","grin-tears":"Grin Tears","grin-tongue":"Grin Tongue","grin-tongue-squint":"Grin Tongue Squint","grin-tongue-wink":"Grin Tongue Wink","grin-wink":"Grin Wink","grip-horizontal":"Grip Horizontal","grip-lines":"Grip Lines","grip-lines-vertical":"Grip Lines Vertical","grip-vertical":"Grip Vertical","guitar":"Guitar","h-square":"H Square","hamburger":"Hamburger","hammer":"Hammer","hamsa":"Hamsa","hand-holding":"Hand Holding","hand-holding-heart":"Hand Holding Heart","hand-holding-usd":"Hand Holding Usd","hand-lizard":"Hand Lizard","hand-middle-finger":"Hand Middle Finger","hand-paper":"Hand Paper","hand-peace":"Hand Peace","hand-point-down":"Hand Point Down","hand-point-left":"Hand Point Left","hand-point-right":"Hand Point Right","hand-point-up":"Hand Point Up","hand-pointer":"Hand Pointer","hand-rock":"Hand Rock","hand-scissors":"Hand Scissors","hand-spock":"Hand Spock","hands":"Hands","hands-helping":"Hands Helping","handshake":"Handshake","hanukiah":"Hanukiah","hard-hat":"Hard Hat","hashtag":"Hashtag","hat-cowboy":"Hat Cowboy","hat-cowboy-side":"Hat Cowboy Side","hat-wizard":"Hat Wizard","hdd":"Hdd","heading":"Heading","headphones":"Headphones","headphones-alt":"Headphones Alt","headset":"Headset","heart":"Heart","heart-broken":"Heart Broken","heartbeat":"Heartbeat","helicopter":"Helicopter","highlighter":"Highlighter","hiking":"Hiking","hippo":"Hippo","history":"History","hockey-puck":"Hockey Puck","holly-berry":"Holly Berry","home":"Home","horse":"Horse","horse-head":"Horse Head","hospital":"Hospital","hospital-alt":"Hospital Alt","hospital-symbol":"Hospital Symbol","hot-tub":"Hot Tub","hotdog":"Hotdog","hotel":"Hotel","hourglass":"Hourglass","hourglass-end":"Hourglass End","hourglass-half":"Hourglass Half","hourglass-start":"Hourglass Start","house-damage":"House Damage","hryvnia":"Hryvnia","i-cursor":"I Cursor","ice-cream":"Ice Cream","icicles":"Icicles","icons":"Icons","id-badge":"Id Badge","id-card":"Id Card","id-card-alt":"Id Card Alt","igloo":"Igloo","image":"Image","images":"Images","inbox":"Inbox","indent":"Indent","industry":"Industry","infinity":"Infinity","info":"Info","info-circle":"Info Circle","italic":"Italic","jedi":"Jedi","joint":"Joint","journal-whills":"Journal Whills","kaaba":"Kaaba","key":"Key","keyboard":"Keyboard","khanda":"Khanda","kiss":"Kiss","kiss-beam":"Kiss Beam","kiss-wink-heart":"Kiss Wink Heart","kiwi-bird":"Kiwi Bird","landmark":"Landmark","language":"Language","laptop":"Laptop","laptop-code":"Laptop Code","laptop-medical":"Laptop Medical","laugh":"Laugh","laugh-beam":"Laugh Beam","laugh-squint":"Laugh Squint","laugh-wink":"Laugh Wink","layer-group":"Layer Group","leaf":"Leaf","lemon":"Lemon","less-than":"Less Than","less-than-equal":"Less Than Equal","level-down-alt":"Level Down Alt","level-up-alt":"Level Up Alt","life-ring":"Life Ring","lightbulb":"Lightbulb","link":"Link","lira-sign":"Lira Sign","list":"List","list-alt":"List Alt","list-ol":"List Ol","list-ul":"List Ul","location-arrow":"Location Arrow","lock":"Lock","lock-open":"Lock Open","long-arrow-alt-down":"Long Arrow Alt Down","long-arrow-alt-left":"Long Arrow Alt Left","long-arrow-alt-right":"Long Arrow Alt Right","long-arrow-alt-up":"Long Arrow Alt Up","low-vision":"Low Vision","luggage-cart":"Luggage Cart","magic":"Magic","magnet":"Magnet","mail-bulk":"Mail Bulk","male":"Male","map":"Map","map-marked":"Map Marked","map-marked-alt":"Map Marked Alt","map-marker":"Map Marker","map-marker-alt":"Map Marker Alt","map-pin":"Map Pin","map-signs":"Map Signs","marker":"Marker","mars":"Mars","mars-double":"Mars Double","mars-stroke":"Mars Stroke","mars-stroke-h":"Mars Stroke H","mars-stroke-v":"Mars Stroke V","mask":"Mask","medal":"Medal","medkit":"Medkit","meh":"Meh","meh-blank":"Meh Blank","meh-rolling-eyes":"Meh Rolling Eyes","memory":"Memory","menorah":"Menorah","mercury":"Mercury","meteor":"Meteor","microchip":"Microchip","microphone":"Microphone","microphone-alt":"Microphone Alt","microphone-alt-slash":"Microphone Alt Slash","microphone-slash":"Microphone Slash","microscope":"Microscope","minus":"Minus","minus-circle":"Minus Circle","minus-square":"Minus Square","mitten":"Mitten","mobile":"Mobile","mobile-alt":"Mobile Alt","money-bill":"Money Bill","money-bill-alt":"Money Bill Alt","money-bill-wave":"Money Bill Wave","money-bill-wave-alt":"Money Bill Wave Alt","money-check":"Money Check","money-check-alt":"Money Check Alt","monument":"Monument","moon":"Moon","mortar-pestle":"Mortar Pestle","mosque":"Mosque","motorcycle":"Motorcycle","mountain":"Mountain","mouse":"Mouse","mouse-pointer":"Mouse Pointer","mug-hot":"Mug Hot","music":"Music","network-wired":"Network Wired","neuter":"Neuter","newspaper":"Newspaper","not-equal":"Not Equal","notes-medical":"Notes Medical","object-group":"Object Group","object-ungroup":"Object Ungroup","oil-can":"Oil Can","om":"Om","otter":"Otter","outdent":"Outdent","pager":"Pager","paint-brush":"Paint Brush","paint-roller":"Paint Roller","palette":"Palette","pallet":"Pallet","paper-plane":"Paper Plane","paperclip":"Paperclip","parachute-box":"Parachute Box","paragraph":"Paragraph","parking":"Parking","passport":"Passport","pastafarianism":"Pastafarianism","paste":"Paste","pause":"Pause","pause-circle":"Pause Circle","paw":"Paw","peace":"Peace","pen":"Pen","pen-alt":"Pen Alt","pen-fancy":"Pen Fancy","pen-nib":"Pen Nib","pen-square":"Pen Square","pencil-alt":"Pencil Alt","pencil-ruler":"Pencil Ruler","people-carry":"People Carry","pepper-hot":"Pepper Hot","percent":"Percent","percentage":"Percentage","person-booth":"Person Booth","phone":"Phone","\\uf879alt":"\\uf879alt","phone-slash":"Phone Slash","phone-square":"Phone Square","\\uf87bsquare-alt":"\\uf87bsquare Alt","phone-volume":"Phone Volume","\\uf87cvideo":"\\uf87cvideo","piggy-bank":"Piggy Bank","pills":"Pills","pizza-slice":"Pizza Slice","place-of-worship":"Place Of Worship","plane":"Plane","plane-arrival":"Plane Arrival","plane-departure":"Plane Departure","play":"Play","play-circle":"Play Circle","plug":"Plug","plus":"Plus","plus-circle":"Plus Circle","plus-square":"Plus Square","podcast":"Podcast","poll":"Poll","poll-h":"Poll H","poo":"Poo","poo-storm":"Poo Storm","poop":"Poop","portrait":"Portrait","pound-sign":"Pound Sign","power-off":"Power Off","pray":"Pray","praying-hands":"Praying Hands","prescription":"Prescription","prescription-bottle":"Prescription Bottle","prescription-bottle-alt":"Prescription Bottle Alt","print":"Print","procedures":"Procedures","project-diagram":"Project Diagram","puzzle-piece":"Puzzle Piece","qrcode":"Qrcode","question":"Question","question-circle":"Question Circle","quidditch":"Quidditch","quote-left":"Quote Left","quote-right":"Quote Right","quran":"Quran","radiation":"Radiation","radiation-alt":"Radiation Alt","rainbow":"Rainbow","random":"Random","receipt":"Receipt","record-vinyl":"Record Vinyl","recycle":"Recycle","redo":"Redo","redo-alt":"Redo Alt","registered":"Registered","\\uf87dformat":"\\uf87dformat","reply":"Reply","reply-all":"Reply All","republican":"Republican","restroom":"Restroom","retweet":"Retweet","ribbon":"Ribbon","ring":"Ring","road":"Road","robot":"Robot","rocket":"Rocket","route":"Route","rss":"Rss","rss-square":"Rss Square","ruble-sign":"Ruble Sign","ruler":"Ruler","ruler-combined":"Ruler Combined","ruler-horizontal":"Ruler Horizontal","ruler-vertical":"Ruler Vertical","running":"Running","rupee-sign":"Rupee Sign","sad-cry":"Sad Cry","sad-tear":"Sad Tear","satellite":"Satellite","satellite-dish":"Satellite Dish","save":"Save","school":"School","screwdriver":"Screwdriver","scroll":"Scroll","sd-card":"Sd Card","search":"Search","search-dollar":"Search Dollar","search-location":"Search Location","search-minus":"Search Minus","search-plus":"Search Plus","seedling":"Seedling","server":"Server","shapes":"Shapes","share":"Share","share-alt":"Share Alt","share-alt-square":"Share Alt Square","share-square":"Share Square","shekel-sign":"Shekel Sign","shield-alt":"Shield Alt","ship":"Ship","shipping-fast":"Shipping Fast","shoe-prints":"Shoe Prints","shopping-bag":"Shopping Bag","shopping-basket":"Shopping Basket","shopping-cart":"Shopping Cart","shower":"Shower","shuttle-van":"Shuttle Van","sign":"Sign","sign-in-alt":"Sign In Alt","sign-language":"Sign Language","sign-out-alt":"Sign Out Alt","signal":"Signal","signature":"Signature","sim-card":"Sim Card","sitemap":"Sitemap","skating":"Skating","skiing":"Skiing","skiing-nordic":"Skiing Nordic","skull":"Skull","skull-crossbones":"Skull Crossbones","slash":"Slash","sleigh":"Sleigh","sliders-h":"Sliders H","smile":"Smile","smile-beam":"Smile Beam","smile-wink":"Smile Wink","smog":"Smog","smoking":"Smoking","smoking-ban":"Smoking Ban","sms":"Sms","snowboarding":"Snowboarding","snowflake":"Snowflake","snowman":"Snowman","snowplow":"Snowplow","socks":"Socks","solar-panel":"Solar Panel","sort":"Sort","sort-alpha-down":"Sort Alpha Down","sort-alpha-down-alt":"Sort Alpha Down Alt","sort-alpha-up":"Sort Alpha Up","sort-alpha-up-alt":"Sort Alpha Up Alt","sort-amount-down":"Sort Amount Down","sort-amount-down-alt":"Sort Amount Down Alt","sort-amount-up":"Sort Amount Up","sort-amount-up-alt":"Sort Amount Up Alt","sort-down":"Sort Down","sort-numeric-down":"Sort Numeric Down","sort-numeric-down-alt":"Sort Numeric Down Alt","sort-numeric-up":"Sort Numeric Up","sort-numeric-up-alt":"Sort Numeric Up Alt","sort-up":"Sort Up","spa":"Spa","space-shuttle":"Space Shuttle","spell-check":"Spell Check","spider":"Spider","spinner":"Spinner","splotch":"Splotch","spray-can":"Spray Can","square":"Square","square-full":"Square Full","square-root-alt":"Square Root Alt","stamp":"Stamp","star":"Star","star-and-crescent":"Star And Crescent","star-half":"Star Half","star-half-alt":"Star Half Alt","star-of-david":"Star Of David","star-of-life":"Star Of Life","step-backward":"Step Backward","step-forward":"Step Forward","stethoscope":"Stethoscope","sticky-note":"Sticky Note","stop":"Stop","stop-circle":"Stop Circle","stopwatch":"Stopwatch","store":"Store","store-alt":"Store Alt","stream":"Stream","street-view":"Street View","strikethrough":"Strikethrough","stroopwafel":"Stroopwafel","subscript":"Subscript","subway":"Subway","suitcase":"Suitcase","suitcase-rolling":"Suitcase Rolling","sun":"Sun","superscript":"Superscript","surprise":"Surprise","swatchbook":"Swatchbook","swimmer":"Swimmer","swimming-pool":"Swimming Pool","synagogue":"Synagogue","sync":"Sync","sync-alt":"Sync Alt","syringe":"Syringe","table":"Table","table-tennis":"Table Tennis","tablet":"Tablet","tablet-alt":"Tablet Alt","tablets":"Tablets","tachometer-alt":"Tachometer Alt","tag":"Tag","tags":"Tags","tape":"Tape","tasks":"Tasks","taxi":"Taxi","teeth":"Teeth","teeth-open":"Teeth Open","temperature-high":"Temperature High","temperature-low":"Temperature Low","tenge":"Tenge","terminal":"Terminal","text-height":"Text Height","text-width":"Text Width","th":"Th","th-large":"Th Large","th-list":"Th List","theater-masks":"Theater Masks","thermometer":"Thermometer","thermometer-empty":"Thermometer Empty","thermometer-full":"Thermometer Full","thermometer-half":"Thermometer Half","thermometer-quarter":"Thermometer Quarter","thermometer-three-quarters":"Thermometer Three Quarters","thumbs-down":"Thumbs Down","thumbs-up":"Thumbs Up","thumbtack":"Thumbtack","ticket-alt":"Ticket Alt","times":"Times","times-circle":"Times Circle","tint":"Tint","tint-slash":"Tint Slash","tired":"Tired","toggle-off":"Toggle Off","toggle-on":"Toggle On","toilet":"Toilet","toilet-paper":"Toilet Paper","toolbox":"Toolbox","tools":"Tools","tooth":"Tooth","torah":"Torah","torii-gate":"Torii Gate","tractor":"Tractor","trademark":"Trademark","traffic-light":"Traffic Light","trailer":"Trailer","train":"Train","tram":"Tram","transgender":"Transgender","transgender-alt":"Transgender Alt","trash":"Trash","trash-alt":"Trash Alt","trash-restore":"Trash Restore","trash-restore-alt":"Trash Restore Alt","tree":"Tree","trophy":"Trophy","truck":"Truck","truck-loading":"Truck Loading","truck-monster":"Truck Monster","truck-moving":"Truck Moving","truck-pickup":"Truck Pickup","tshirt":"Tshirt","tty":"Tty","tv":"Tv","umbrella":"Umbrella","umbrella-beach":"Umbrella Beach","underline":"Underline","undo":"Undo","undo-alt":"Undo Alt","universal-access":"Universal Access","university":"University","unlink":"Unlink","unlock":"Unlock","unlock-alt":"Unlock Alt","upload":"Upload","user":"User","user-alt":"User Alt","user-alt-slash":"User Alt Slash","user-astronaut":"User Astronaut","user-check":"User Check","user-circle":"User Circle","user-clock":"User Clock","user-cog":"User Cog","user-edit":"User Edit","user-friends":"User Friends","user-graduate":"User Graduate","user-injured":"User Injured","user-lock":"User Lock","user-md":"User Md","user-minus":"User Minus","user-ninja":"User Ninja","user-nurse":"User Nurse","user-plus":"User Plus","user-secret":"User Secret","user-shield":"User Shield","user-slash":"User Slash","user-tag":"User Tag","user-tie":"User Tie","user-times":"User Times","users":"Users","users-cog":"Users Cog","utensil-spoon":"Utensil Spoon","utensils":"Utensils","vector-square":"Vector Square","venus":"Venus","venus-double":"Venus Double","venus-mars":"Venus Mars","vial":"Vial","vials":"Vials","video":"Video","video-slash":"Video Slash","vihara":"Vihara","voicemail":"Voicemail","volleyball-ball":"Volleyball Ball","volume-down":"Volume Down","volume-mute":"Volume Mute","volume-off":"Volume Off","volume-up":"Volume Up","vote-yea":"Vote Yea","vr-cardboard":"Vr Cardboard","walking":"Walking","wallet":"Wallet","warehouse":"Warehouse","water":"Water","wave-square":"Wave Square","weight":"Weight","weight-hanging":"Weight Hanging","wheelchair":"Wheelchair","wifi":"Wifi","wind":"Wind","window-close":"Window Close","window-maximize":"Window Maximize","window-minimize":"Window Minimize","window-restore":"Window Restore","wine-bottle":"Wine Bottle","wine-glass":"Wine Glass","wine-glass-alt":"Wine Glass Alt","won-sign":"Won Sign","wrench":"Wrench","x-ray":"X Ray","yen-sign":"Yen Sign","yin-yang":"Yin Yang"}}',
                'order' => 6,
            ),
            58 => 
            array (
                'id' => 59,
                'data_type_id' => 9,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            59 => 
            array (
                'id' => 60,
                'data_type_id' => 9,
                'field' => 'coupon',
                'type' => 'text',
                'display_name' => 'Coupon Code',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            60 => 
            array (
                'id' => 61,
                'data_type_id' => 9,
                'field' => 'discount',
                'type' => 'number',
            'display_name' => 'Discount (%)',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            61 => 
            array (
                'id' => 62,
                'data_type_id' => 9,
                'field' => 'limit',
                'type' => 'number',
                'display_name' => 'Can be used max',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            62 => 
            array (
                'id' => 63,
                'data_type_id' => 9,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            63 => 
            array (
                'id' => 64,
                'data_type_id' => 9,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            64 => 
            array (
                'id' => 65,
                'data_type_id' => 10,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            65 => 
            array (
                'id' => 66,
                'data_type_id' => 10,
                'field' => 'is_active',
                'type' => 'checkbox',
                'display_name' => 'Is Active',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            66 => 
            array (
                'id' => 67,
                'data_type_id' => 10,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Short Lowercase Name',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            67 => 
            array (
                'id' => 68,
                'data_type_id' => 10,
                'field' => 'title',
                'type' => 'text',
            'display_name' => 'Title (For Human)',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            68 => 
            array (
                'id' => 69,
                'data_type_id' => 10,
                'field' => 'file',
                'type' => 'file',
                'display_name' => 'File',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            69 => 
            array (
                'id' => 70,
                'data_type_id' => 10,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ),
            70 => 
            array (
                'id' => 71,
                'data_type_id' => 10,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            71 => 
            array (
                'id' => 72,
                'data_type_id' => 11,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            72 => 
            array (
                'id' => 73,
                'data_type_id' => 11,
                'field' => 'invoice_id',
                'type' => 'text',
                'display_name' => 'Invoice Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            73 => 
            array (
                'id' => 74,
                'data_type_id' => 11,
                'field' => 'user_id',
                'type' => 'text',
                'display_name' => 'User Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            74 => 
            array (
                'id' => 75,
                'data_type_id' => 11,
                'field' => 'credits',
                'type' => 'text',
                'display_name' => 'Credits',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            75 => 
            array (
                'id' => 76,
                'data_type_id' => 11,
                'field' => 'type',
                'type' => 'text',
                'display_name' => 'Type',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            76 => 
            array (
                'id' => 77,
                'data_type_id' => 11,
                'field' => 'comment',
                'type' => 'text',
                'display_name' => 'Comment',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ),
            77 => 
            array (
                'id' => 78,
                'data_type_id' => 11,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
            78 => 
            array (
                'id' => 79,
                'data_type_id' => 11,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            79 => 
            array (
                'id' => 80,
                'data_type_id' => 11,
                'field' => 'credit_log_belongsto_invoice_relationship',
                'type' => 'relationship',
                'display_name' => 'invoices',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Invoice","table":"invoices","type":"belongsTo","column":"invoice_id","key":"id","label":"description","pivot_table":"brandbooks","pivot":"0","taggable":null}',
                'order' => 9,
            ),
            80 => 
            array (
                'id' => 81,
                'data_type_id' => 11,
                'field' => 'credit_log_belongsto_user_relationship',
                'type' => 'relationship',
                'display_name' => 'users',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"user_id","key":"id","label":"name","pivot_table":"brandbooks","pivot":"0","taggable":null}',
                'order' => 10,
            ),
        ));
        

}
}