<?php
return [
    'tabs' => [
        [
            "title" => "Introduction",
            "icon" => "icon-menu-introduction",
            "slug" => "introduction",
            "order" => 1,
            "is_default" => true,
        ],
        [
            "title" => "Vision",
            "icon" => "icon-menu-vision",
            "slug" => "vision",
            "order" => 2,
            "is_default" => true,
        ],
        [
            "title" => "Mission",
            "icon" => "icon-menu-mission",
            "slug" => "mission",
            "order" => 3,
            "is_default" => true,
        ],
        [
            "title" => "Core Values",
            "icon" => "icon-menu-values",
            "slug" => "core-values",
            "order" => 4,
            "is_default" => true,
        ],
        [
            "title" => "Brand Archetype",
            "icon" => "icon-menu-archetype",
            "slug" => "brand-archetype",
            "order" => 5,
            "is_default" => true,
        ],
        [
            "title" => "Our Logo",
            "icon" => "icon-menu-logo",
            "slug" => "logo",
            "order" => 6,
            "is_default" => true,
        ],
        [
            "title" => "Clear Space",
            "icon" => "icon-menu-space",
            "slug" => "clear-space",
            "order" => 7,
            "is_default" => true,
        ],
        [
            "title" => "Minimum Size",
            "icon" => "icon-menu-size",
            "slug" => "minimum-size",
            "order" => 8,
            "is_default" => true,
        ],
        [
            "title" => "Logo Misuse",
            "icon" => "icon-menu-misuse",
            "slug" => "logo-misuse",
            "order" => 9,
            "is_default" => true,
        ],
        [
            "title" => "Feature Icons",
            "icon" => "icon-menu-feature",
            "slug" => "feature-icons",
            "order" => 10,
            "is_default" => true,
        ],
        [
            "title" => "Color Palette",
            "icon" => "icon-menu-palette",
            "slug" => "color-palette",
            "order" => 11,
            "is_default" => true,
        ],
        [
            "title" => "Our Fonts",
            "icon" => "icon-menu-fonts",
            "slug" => "our-fonts",
            "order" => 12,
            "is_default" => true,
        ],
        [
            "title" => "Brand Designer",
            "icon" => "icon-menu-designer",
            "slug" => "brand-designer",
            "order" => 13,
            "is_default" => true,
        ],
    ],
];
